import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import CategoryPicker from '../components/CategoryPicker';
import FeaturedBlogs from '../components/FeaturedBlogs';
import FeaturedProducts from '../components/FeaturedProducts';
import { BannerData, BlogData, Product } from '../types';

interface HomepageProps {
  dataBanner: BannerData;
  dataFeaturedProducts: Product[];
  dataFeaturedBlogs: BlogData[];
}

const Home: NextPage<HomepageProps> = ({ dataBanner, dataFeaturedProducts, dataFeaturedBlogs }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner dataBanner={dataBanner} />

      <CategoryPicker />

      <FeaturedProducts featuredProducts={dataFeaturedProducts} />

      <FeaturedBlogs featuredBlogs={dataFeaturedBlogs} />
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const resBanner = await fetch('http://localhost:5001/banner_content');
  const dataBanner: BannerData = await resBanner.json();

  const resFeaturedProducts = await fetch('http://localhost:5001/products/?_limit=4');
  const dataFeaturedProducts: Product[] = await resFeaturedProducts.json();

  const resFeaturedBlogs = await fetch('http://localhost:5001/blogs/?_limit=3');
  const dataFeaturedBlogs: BlogData[] = await resFeaturedBlogs.json();

  return {
    props: {
      dataBanner,
      dataFeaturedProducts,
      dataFeaturedBlogs,
    },
  };
};
